Two portability / build fixes (#401)
* OgreSilentMemory.h defines "silent" versions of memset and friends for use with the GCC compiler. It correctly tests for "__GNUC__" for use. However, "nonnull" in gcc is an attribute spellt something like __attribute__((nunnull(1,2))). The functions here instead use glibc macros from sys/cdefs.h like __nonnull, so also test for the availability of those macros.

(MING32 was presumably listed because it doesn't define those glibc
macros. The way forward is not to list all operating systems which
don't use glibc.)

* OgreMain/include/OgreBitwise.h defines bswapNN functions. Some operating systems already define macros with those names. Rather than list all operating systems for which this true, undefine those macros for the duration of OgreBitwise.h and redefine them at the end.

* OgreSceneFormatExporter.cpp: Build fix

Recent compilers fail with

.../ogre-next/Components/SceneFormat/src/OgreSceneFormatExporter.cpp: In member function ‘const char* Ogre::SceneFormatExporter::encodeDouble(double)’:
.../ogre-next/Components/SceneFormat/src/OgreSceneFormatExporter.cpp:171:17: error: ‘isfinite’ was not declared in this scope; did you mean ‘std::isfinite’?

Simplest fix is to drop support for MSVC < version 1800.
(see pull request 372)