[Vk] Require linear sampling support for hardware mipmap generation, fallback to software if not supported. Utility of mipmap generation without ability to then linearly sample from it is questionable, but who knows. At least it produces validation errors later, at usage site. Catched on Xclipse 920 (Samsung S22) for R16G16B16A16 pixel format
ERROR: [Validation] Code 0 : vkCmdBlitImage(): srcImage (VkImage 0x75d000000075d[___tempMipmapTexture]) was created with format VK_FORMAT_R16G16B16A16_UNORM and tiling VK_IMAGE_TILING_OPTIMAL which have VkFormatFeatureFlags2 (VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_BIT|VK_FORMAT_FEATURE_2_STORAGE_IMAGE_BIT|VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT|VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BLEND_BIT|VK_FORMAT_FEATURE_2_BLIT_SRC_BIT|VK_FORMAT_FEATURE_2_BLIT_DST_BIT|VK_FORMAT_FEATURE_2_TRANSFER_SRC_BIT|VK_FORMAT_FEATURE_2_TRANSFER_DST_BIT) which in turn is missing the required feature VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_FILTER_LINEAR_BIT.
The Vulkan spec states: If filter is VK_FILTER_LINEAR, then the format features of srcImage must contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT (https://docs.vulkan.org/spec/latest/chapters/copies.html#VUID-vkCmdBlitImage-filter-02001)